export default {
  SWITCH_CITY: `SWITCH_CITY`,
  SORT_OFFERS: `SORT_OFFERS`,
  LOAD_HOTELS: `LOAD_HOTELS`,
  SWITCH_LOADING_STATE: `SWITCH_LOADING_STATE`,
  REQUIRE_AUTHORIZATION: `REQUIRE_AUTHORIZATION`,
  SING_IN: `SING_IN`,
  SET_USER_DATA: `SET_USER_DATA`
};
