export default {
  SWITCH_CITY: `SWITCH_CITY`,
  SORT_OFFERS: `SORT_OFFERS`,
  LOAD_HOTELS: `LOAD_HOTELS`,
  SWITCH_LOADING_STATE: `SWITCH_LOADING_STATE`,
  SING_IN: `SING_IN`,
  SET_FAVORITE_OFFER: `SET_FAVORITE_OFFER`,
  GET_FAVORITE_OFFERS: `GET_FAVORITE_OFFERS`,
  GET_COMMENTS: `GET_COMMENTS`,
  SET_OFFER_REF: `SET_OFFER_REF`,
  DELETE_OFFER_REF: `DELETE_OFFER_REF`,
  SET_PRICE_RANGE: `SET_PRICE_RANGE`,
  RESET_CITY_FILTERS: `RESET_CITY_FILTERS`,
  SET_CITY_RATING: `SET_CITY_RATING`
};
