export default {
  SWITCH_CITY: `SWITCH_CITY`,
  SORT_OFFERS: `SORT_OFFERS`,
  LOAD_HOTELS: `LOAD_HOTELS`,
  SWITCH_LOADING_STATE: `SWITCH_LOADING_STATE`,
  SING_IN: `SING_IN`,
  SET_FAVORITE_OFFER: `SET_FAVORITE_OFFER`,
  GET_FAVORITE_OFFERS: `GET_FAVORITE_OFFERS`
};
